# Generated by Django 5.0.6 on 2024-06-27 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BandApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='song_lyrics',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='song_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='date_released',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
